FROM quicdependencies as srv

WORKDIR $HOME/quicsrv

COPY srv ./srv
COPY cmd ./cmd
COPY common ./common
COPY md5 ./md5
COPY serialize ./serialize
COPY tls ./tls
COPY vendor ./vendor
COPY go.mod \
  go.sum ./

RUN go build -mod=vendor -o quicsrv ./cmd/srv/main.go

EXPOSE 1234

ENTRYPOINT ["./quicsrv"]