FROM quicdependencies as cli

WORKDIR $HOME/quiccli

COPY cli ./cli
COPY cmd ./cmd
COPY common ./common
COPY md5 ./md5
COPY serialize ./serialize
COPY tls ./tls
COPY go.mod \
  go.sum ./

RUN go build -o quiccli ./cmd/cli/main.go

EXPOSE 1235

ENTRYPOINT ["./quiccli"]