FROM quicdependencies as cli

WORKDIR $HOME/quiccli

COPY cli ./cli
COPY cmd ./cmd
COPY common ./common
COPY go.mod \
  go.sum ./

RUN go build -o quiccli ./cmd/cli/main.go

EXPOSE 1235

ENTRYPOINT ["./quiccli"]