FROM quicdependencies as srv

WORKDIR $HOME/quicsrv

COPY srv ./srv
COPY cmd ./cmd
COPY common ./common
COPY md5 ./md5
COPY serialize ./serialize
COPY tls ./tls
COPY go.mod \
  go.sum ./

RUN go build -o quicsrv ./cmd/srv/main.go

EXPOSE 1234

ENTRYPOINT ["./quicsrv"]